# -*- coding: utf-8 -*-
"""retail_ai_ml_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zFjSbzGMvLp9NCd-J1lGaGJnSRRD7Wf

**RETAIL PROJECT (AI & ML)**

Team Member:

Premchand Mahanta

Neilkanth Loke

Aayush Sindhe

Talluri Venkata Ramanuja Ramaseshabhay

->**Importing retail_price.csv**
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

"""->**Loads retail pricing data from a CSV file into a pandas DataFrame and prints the top rows to preview the content**"""

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['retail_price.csv']))
print(df.head())  # Display the first few rows

"""->**To clean the data and analyze profitability by comparing the product's price with competitors' prices.**"""

# Check for missing values
print(df.isnull().sum())

# Drop rows with missing critical fields
df.dropna(subset=['qty', 'unit_price', 'total_price', 'freight_price', 'comp_1', 'comp_2', 'comp_3'], inplace=True)

# Estimate Cost of Goods Sold (COGS) as a proxy: unit_price - avg competitor price
df['avg_comp_price'] = df[['comp_1', 'comp_2', 'comp_3']].mean(axis=1)
df['estimated_margin'] = df['unit_price'] - df['avg_comp_price']
df['profit'] = df['qty'] * df['estimated_margin']

"""->**To visualize pricing trends across categories and explore relationships between key business metrics like cost, margin, and profit.**"""

# Plot the distribution of unit prices by product category
plt.figure(figsize=(10, 6))
sns.boxplot(x='product_category_name', y='unit_price', data=df)
plt.xticks(rotation=90)
plt.title('Unit Price Distribution by Category')
plt.show()

# Correlation heatmap
plt.figure(figsize=(12, 8))
corr = df[['unit_price', 'freight_price', 'avg_comp_price', 'estimated_margin', 'profit']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""->**To analyze the pricing impact on sales and profit for a specific product, helping identify the optimal price point for maximizing revenue or profit.**"""

# Group by product and price to see aggregated performance
agg = df.groupby(['product_id', 'unit_price']).agg({
    'qty': 'sum',
    'profit': 'sum'
}).reset_index()

# Visualize sales volume vs price for a sample product
sample_product = agg[agg['product_id'] == 'bed1']
plt.figure(figsize=(8, 5))
sns.lineplot(x='unit_price', y='qty', data=sample_product, marker='o', label='Quantity Sold')
sns.lineplot(x='unit_price', y='profit', data=sample_product, marker='o', label='Profit')
plt.title('Sales & Profit by Price (bed1)')
plt.xlabel('Unit Price')
plt.legend()
plt.show()