# -*- coding: utf-8 -*-
"""retail_ai_ml_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zFjSbzGMvLp9NCd-J1lGaGJnSRRD7Wf

**RETAIL PROJECT (AI & ML)**

**Name:Premchand Mahanta**

The Retail Price and Profit Prediction System uses data analysis and machine learning to study retail product pricing and profitability. The dataset is processed to calculate competitor pricing and profit margins. Visualizations are used to understand relationships between price, quantity, freight cost, and profit. A machine learning model using Linear Regression from scikit-learn is trained to predict product profit based on these factors. This helps in analyzing pricing strategies and making data-driven decisions to improve profitability.
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

"""**Load Dataset & Data Cleaning**"""

df = pd.read_csv("retail_price.csv")

df = df.dropna()

print(df.head())

"""**Calculate Average Competitor Price & Calculate Estimated Margin and Profit**"""

df['avg_comp_price'] = df[['comp_1','comp_2','comp_3']].mean(axis=1)

df['estimated_margin'] = df['unit_price'] - df['avg_comp_price']

df['profit'] = df['qty'] * df['estimated_margin']

print(df.head())

"""**Price Distribution Visualization**"""

plt.figure()
sns.boxplot(x='product_category_name', y='unit_price', data=df)
plt.xticks(rotation=90)
plt.title("Price Distribution by Category")
plt.show()

"""**Correlation Heatmap**"""

plt.figure()
sns.heatmap(df[['unit_price','freight_price','avg_comp_price','qty','profit']].corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""**Feature Selection**"""

X = df[['qty','unit_price','freight_price','avg_comp_price']]
y = df['profit']

"""**Train-Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()

"""**Train Machine Learning Model**"""

model = LinearRegression()

model.fit(X_train, y_train)

"""**Predict Test Data**"""

y_pred = model.predict(X_test)

"""Model Evaluation"""

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

"""**Predict Profit for New Product**"""

new_product = [[50, 200, 20, 180]]

predicted_profit = model.predict(new_product)

print("Predicted Profit:", predicted_profit[0])